# Generated by Django 6.0.5 on 2026-05-18 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('core', '0001_initial'),
        ('customers', '0002_remove_customer_customers_c_tenant__0aea56_idx_and_more'),
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_tenant__9894a8_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_tenant__e6671e_idx',
        ),
        migrations.AlterField(
            model_name='booking',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.tenant'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['start_date'], name='bookings_bo_start_d_3e8155_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_status'], name='bookings_bo_booking_9deb2e_idx'),
        ),
    ]
