# Generated by Django 6.0.5 on 2026-06-03 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_booking_date_booking_booking_id_booking_cnic_and_more'),
        ('decorations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='decoration_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='decorations.decorationpackage'),
        ),
    ]
