# Generated by Django 6.0.4 on 2026-06-20 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_marriagehallpagevisibility_maintenance_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarriageHallPageLive',
            fields=[
            ],
            options={
                'verbose_name': 'MH page — show in menu',
                'verbose_name_plural': '1 · MH pages — Show in menu (live)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bookings.marriagehallpagevisibility',),
        ),
        migrations.CreateModel(
            name='MarriageHallPageMaintenance',
            fields=[
            ],
            options={
                'verbose_name': 'MH page — maintenance',
                'verbose_name_plural': '2 · MH pages — Maintenance & reopen time',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bookings.marriagehallpagevisibility',),
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'MH booking', 'verbose_name_plural': '3 · MH — Bookings'},
        ),
    ]
