# Generated by Django 6.0.4 on 2026-05-20 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecorationPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tier', models.CharField(choices=[('ESSENTIAL', 'Essential'), ('CLASSIC', 'Classic'), ('PREMIUM', 'Premium'), ('ROYAL', 'Royal'), ('CUSTOM', 'Custom quote')], default='CLASSIC', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('included_items', models.JSONField(default=list, help_text='List of line items included in this package, e.g. stage backdrop, LED panels')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('setup_hours', models.PositiveSmallIntegerField(default=4, help_text='Estimated on-site setup time')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decoration_packages', to='core.tenant')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='decoration_pkg_unique_name_per_tenant')],
            },
        ),
    ]
