# Generated by Django 6.0.4 on 2026-06-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='landing/gallery/')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('MARRIAGE_HALL', 'Marriage Hall'), ('WEDDING_STAGE', 'Wedding Stage'), ('GUEST_ROOM', 'Guest Room'), ('DINING', 'Dining Area'), ('RECEPTION', 'Reception Area'), ('OUTDOOR', 'Outdoor Event Area'), ('OTHER', 'Other')], default='MARRIAGE_HALL', max_length=30)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True, default='')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='landing/hero/')),
                ('button_text', models.CharField(default='Get Started', max_length=80)),
                ('button_link', models.CharField(default='/login', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LandingFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LandingStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('hero', 'Hero - below slider'), ('trust', 'Trust & Social Proof'), ('success', 'Success Statistics')], max_length=20)),
                ('label', models.CharField(max_length=120)),
                ('value_display', models.CharField(help_text='Shown text e.g. 98% or 10,000+', max_length=40)),
                ('value_number', models.PositiveIntegerField(default=0, help_text='Used for animated counters')),
                ('suffix', models.CharField(blank=True, default='', help_text='e.g. + or %', max_length=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['section', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_photo', models.ImageField(blank=True, null=True, upload_to='landing/testimonials/')),
                ('designation', models.CharField(blank=True, default='', max_length=150)),
                ('review', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
