# Generated by Django 6.0.5 on 2026-05-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('FOOD', 'Food & Beverage'), ('DECORATION', 'Decoration'), ('UTENSIL', 'Utensils & Cutlery'), ('ELECTRONIC', 'Electronics & Lighting'), ('FURNITURE', 'Furniture'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(help_text='e.g., kg, pcs, liters, units', max_length=50)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('last_restocked', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('LOW_STOCK', 'Low Stock'), ('OUT_OF_STOCK', 'Out of Stock')], default='IN_STOCK', max_length=20)),
            ],
        ),
    ]
