# Generated by Django 6.0.5 on 2026-06-03 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_decoration_package'),
        ('core', '0004_delete_notificationlog'),
        ('inventory', '0002_inventoryitem_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.PositiveIntegerField(default=1)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='bookings.booking')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_allocations', to='inventory.inventoryitem')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_inventory', to='core.tenant')),
            ],
            options={
                'unique_together': {('booking', 'inventory_item')},
            },
        ),
    ]
