# Generated by Django 6.0.5 on 2026-06-05 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_restore_notificationlog_prefs'),
        ('guesthouse', '0003_room_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestHousePageVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(max_length=32)),
                ('label', models.CharField(max_length=64)),
                ('is_visible', models.BooleanField(default=True, help_text='Uncheck to hide this page from the Guest House app sidebar and block direct access.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gh_page_visibility', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Guest House page visibility',
                'verbose_name_plural': 'Guest House page visibility',
                'ordering': ['sort_order', 'page_key'],
                'unique_together': {('tenant', 'page_key')},
            },
        ),
    ]
