# Generated by Django 6.0.5 on 2026-06-05 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_restore_notificationlog_prefs'),
        ('guesthouse', '0004_guesthouse_page_visibility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guesthousepagevisibility',
            options={'ordering': ['sort_order', 'page_key'], 'verbose_name': 'GH page hide/show', 'verbose_name_plural': 'GH pages hide/show'},
        ),
        migrations.AddField(
            model_name='room',
            name='extra_guest_fee_per_night',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Extra charge per additional guest per night.', max_digits=12),
        ),
        migrations.AddField(
            model_name='room',
            name='included_guests',
            field=models.PositiveIntegerField(default=0, help_text='Guests included in base rate. 0 = use bed count.'),
        ),
        migrations.CreateModel(
            name='GuestHouseService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('label', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pricing_unit', models.CharField(choices=[('PER_NIGHT', 'Per night'), ('PER_STAY', 'Per stay'), ('PER_GUEST', 'Per guest per night')], default='PER_NIGHT', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gh_services', to='core.tenant')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StayCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('SERVICE', 'Add-on service'), ('CUSTOM', 'Custom charge')], default='SERVICE', max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stay_charges', to='guesthouse.guesthouseservice')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='guesthouse.staybooking')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
