# Generated by Django 6.0.4 on 2026-06-20 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0009_guesthousepagevisibility_maintenance_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestHousePageLive',
            fields=[
            ],
            options={
                'verbose_name': 'GH page — show in menu',
                'verbose_name_plural': '1 · GH pages — Show in menu (live)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('guesthouse.guesthousepagevisibility',),
        ),
        migrations.CreateModel(
            name='GuestHousePageMaintenance',
            fields=[
            ],
            options={
                'verbose_name': 'GH page — maintenance',
                'verbose_name_plural': '2 · GH pages — Maintenance & reopen time',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('guesthouse.guesthousepagevisibility',),
        ),
        migrations.AlterModelOptions(
            name='ghexpense',
            options={'ordering': ['-expense_date', '-id'], 'verbose_name': 'GH expense', 'verbose_name_plural': '7 · GH — Expenses'},
        ),
        migrations.AlterModelOptions(
            name='guesthouseservice',
            options={'ordering': ['sort_order', 'label'], 'verbose_name': 'GH add-on service', 'verbose_name_plural': '4 · GH — Add-on services'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['room_number'], 'verbose_name': 'GH room', 'verbose_name_plural': '3 · GH — Rooms'},
        ),
        migrations.AlterModelOptions(
            name='staybooking',
            options={'ordering': ['-check_in'], 'verbose_name': 'GH stay', 'verbose_name_plural': '5 · GH — Stays & bookings'},
        ),
        migrations.AlterModelOptions(
            name='staycharge',
            options={'ordering': ['id'], 'verbose_name': 'GH stay charge', 'verbose_name_plural': '8 · GH — Stay charges (advanced)'},
        ),
        migrations.AlterModelOptions(
            name='staypayment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'GH payment', 'verbose_name_plural': '6 · GH — Payments'},
        ),
    ]
