# Generated by Django 6.0.5 on 2026-07-16 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0015_staypayment_receipt_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='extra_bed_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='extra_bed_limit',
            field=models.PositiveIntegerField(default=0, help_text='Max extra mattresses beyond included guests.'),
        ),
        migrations.AddField(
            model_name='room',
            name='housekeeping_status',
            field=models.CharField(choices=[('VACANT', 'Vacant'), ('OCCUPIED', 'Occupied'), ('CLEANING', 'Cleaning'), ('MAINTENANCE', 'Maintenance'), ('OUT_OF_ORDER', 'Out of order')], default='VACANT', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='max_guests',
            field=models.PositiveIntegerField(default=0, help_text='Hard cap including extra beds. 0 = included guests (or beds) only.'),
        ),
        migrations.AddField(
            model_name='room',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent suite for this room. Suites must leave this empty.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='guesthouse.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='sellable',
            field=models.BooleanField(default=True, help_text='If false, unit is structural only and cannot be booked.'),
        ),
        migrations.AddField(
            model_name='room',
            name='unit_kind',
            field=models.CharField(choices=[('SUITE', 'Suite'), ('ROOM', 'Room')], default='ROOM', help_text='Suite = sellable parent unit. Room = sellable child or standalone room.', max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='beds',
            field=models.PositiveIntegerField(default=1, help_text='Legacy bed count. Prefer RoomBed rows when present.'),
        ),
        migrations.AlterField(
            model_name='room',
            name='extra_guest_fee_per_night',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Extra bedding / additional guest charge per night.', max_digits=12),
        ),
        migrations.CreateModel(
            name='RoomBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_type', models.CharField(choices=[('KING', 'King'), ('QUEEN', 'Queen'), ('TWIN', 'Twin'), ('SINGLE', 'Single'), ('SOFA', 'Sofa bed'), ('BUNK', 'Bunk')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_configs', to='guesthouse.room')),
            ],
            options={
                'verbose_name': 'GH room bed',
                'verbose_name_plural': '3b · GH — Room beds',
                'ordering': ['id'],
                'unique_together': {('room', 'bed_type')},
            },
        ),
    ]
