# Generated by Django 6.0.5 on 2026-07-16 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tenant_gh_stay_times'),
        ('guesthouse', '0016_suite_room_hierarchy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, help_text='Deprecated. Use UnitMedia rows; kept for legacy data migration.', null=True, upload_to='gh_rooms/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='unit_kind',
            field=models.CharField(choices=[('SUITE', 'Suite'), ('ROOM', 'Room')], default='ROOM', help_text='Type of accommodation unit. Suite = top-level parent (parent must be empty). Room with no parent = independent. Room with parent = belongs to that suite.', max_length=10),
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(blank=True, default='', max_length=40)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gh_amenities', to='core.tenant')),
            ],
            options={
                'verbose_name': 'GH amenity',
                'verbose_name_plural': '3d · GH — Amenities',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UnitAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_links', to='guesthouse.amenity')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_amenities', to='guesthouse.room')),
            ],
            options={
                'verbose_name': 'GH unit amenity',
                'verbose_name_plural': '3e · GH — Unit amenities',
                'unique_together': {('unit', 'amenity')},
            },
        ),
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='units', through='guesthouse.UnitAmenity', to='guesthouse.amenity'),
        ),
        migrations.CreateModel(
            name='UnitMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('ROOM', 'Room'), ('SUITE', 'Suite')], default='ROOM', max_length=10)),
                ('file', models.ImageField(upload_to='gh_unit_media/')),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='guesthouse.room')),
            ],
            options={
                'verbose_name': 'GH unit media',
                'verbose_name_plural': '3c · GH — Unit media',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
