# Generated by Django 6.0.5 on 2026-05-18 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='venue',
            name='venues_venu_tenant__b94139_idx',
        ),
        migrations.AlterField(
            model_name='venue',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='core.tenant'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['status'], name='venues_venu_status_d850d5_idx'),
        ),
    ]
