# Generated by Django 6.0.5 on 2026-06-03 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tenant_fields_usersettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationLog',
        ),
    ]
