# Generated by Django 6.0.4 on 2026-06-20 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_restore_notificationlog_prefs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification log', 'verbose_name_plural': 'SMS & notification log'},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'verbose_name': 'Tenant', 'verbose_name_plural': 'Tenants'},
        ),
    ]
